services:
  - type: web
    name: universal-bot
    env: python
    region: frankfurt
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: SPREADSHEET_NAME
        sync: false
      - key: GOOGLE_SA_JSON
        sync: false
